config/routes.rb
Rails.application.routes.draw do

  root  'home#index'

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update]
  patch 'user/change_is_admin', to: 'users#change_is_admin'

  resources :genres

  patch 'user_genre_infos/add_genre_leader', to: 'user_genre_infos#add_genre_leader'
  patch 'user_genre_infos/destroy_genre_leader', to: 'user_genre_infos#destroy_genre_leader'
  patch 'user_genre_infos/destroy_request', to: 'user_genre_infos#destroy_request'
  resources :user_genre_infos, only: [:create, :update, :destroy]

  resources :events
  get 'event/:id/edit_admins', to: 'events#edit_event_admin', as: :edit_evemt_admins
  resources :event_participations, only: [:create,:update, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :user_genre_infos
	has_many :users, through: :user_genre_infos, #genre.usersが使えるようになる？
					 dependent: :destroy

	def leader_name
		leader_info = self.user_genre_infos.find_by(is_genre_leader: true)
		if leader_info
			return leader_info.user.name
		else
			return '未登録'
		end
	end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])

    @genre1_users_info = UserGenreInfo.where(genre_id: @genre.id, is_valid: true, priority: 1.to_i)
    @genre2_users_info = UserGenreInfo.where(genre_id: @genre.id, is_valid: true, priority: 2)
    @request_users_info = UserGenreInfo.where(genre_id: @genre.id, is_valid: false)

    @genre1_1st_users = []
    @genre1_2nd_users = []
    @genre1_3rd_users = []

    @genre2_1st_users = []
    @genre2_2nd_users = []
    @genre2_3rd_users = []

    # genre1_user = @genre1_users_info.users.order('term') を試す

    @genre1_users_info.each do |genre1_user_info|
      if genre1_user_info.user.term == get_1st_grade_term-2
        @genre1_3rd_users.push(genre1_user_info.user)
      elsif genre1_user_info.user.term == get_1st_grade_term-1
        @genre1_2nd_users.push(genre1_user_info.user)
      elsif genre1_user_info.user.term == get_1st_grade_term
        @genre1_1st_users.push(genre1_user_info.user)
      end
    end

    @genre2_users_info.each do |genre2_user_info|
      if genre2_user_info.user.term == get_1st_grade_term-2
        @genre2_3rd_users.push(genre2_user_info.user)
      elsif genre2_user_info.user.term == get_1st_grade_term-1
        @genre2_2nd_users.push(genre2_user_info.user)
      elsif genre2_user_info.user.term == get_1st_grade_term
        @genre2_1st_users.push(genre2_user_info.user)
      end
    end
  end

  def edit
    #ジャンル名の編集画面
  end

  def update
    #ジャンル名の更新
  end

  def destroy
    #ジャンルの削除
  end

  def new
    #新規ジャンルの登録画面
  end

  def create
    #新規ジャンルの登録処理
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/edit.html.erb
<h1>Genres#edit</h1>
<p>Find me in app/views/genres/edit.html.erb</p>

app/views/genres/index.html.erb
<div class="container">
	 <div class='row'>
		<div class='col-xs-2'></div>
		<div class="col-xs-8 genre-container">
			<% @genres.each do |genre| %>
				  <%=link_to genre.name, genre_path(genre) ,class: "genre-box",:style=>"color:white;"  %>

			<%end%>
		</div>
		<div class='col-xs-2'></div>
	</div>
</div>

app/views/genres/new.html.erb
<h1>Genres#new</h1>
<p>Find me in app/views/genres/new.html.erb</p>

app/views/genres/show.html.erb
<div class="member-container">
	<div class="show_genre_name">
		<%= @genre.name %>
		<p class="genre_member_num"> ：<%= @genre1_users_info.count + @genre2_users_info.count %>名 </p>
	</div>
	<% if flash[:notice]%>
		<div class="alert alert-info">
	      <%= flash[:notice] %>
	    </div>
	<% end %>
	<% if flash[:warning_notice]%>
		<div class="alert alert-warning">
	      <%= flash[:warning_notice] %>
	    </div>
	<% end %>
	<% if flash[:danger_notice]%>
		<div class="alert alert-danger">
	      <%= flash[:danger_notice] %>
	    </div>
	<% end %>
	<div class=member-box>
		<h3>1ジャン</h3>
		<table class="table-sm table-striped">
			<thead>
				<tr>
					<th>代</th>
					<th>名前</th>
					<th>2ジャン</th>
					<th>その他</th>
				</tr>
			</thead>
			<tbody>
				<% @genre1_3rd_users.each do |genre1_3rd_user| %>
					<tr>
						<td class="none_wrap"><%= genre1_3rd_user.term %></td>
						<td><%=link_to genre1_3rd_user.name, user_path(genre1_3rd_user.id),class: "user_name" %></td>
						<td><%= genre1_3rd_user.genre2_name %></td>
						<td>
							<% if genre1_3rd_user.is_admin %>代表<%end%>
							<% if genre1_3rd_user.is_genre_leader? %>部門長<%end%>
						</td>
					</tr>
				<%end%>
				<% @genre1_2nd_users.each do |genre1_2nd_user| %>
					<tr>
						<td class="none_wrap"><%= genre1_2nd_user.term %></td>
						<td><%=link_to genre1_2nd_user.name, user_path(genre1_2nd_user.id),class: "user_name" %></td>
						<td><%= genre1_2nd_user.genre2_name %></td>
						<td>
							<% if genre1_2nd_user.is_admin %>代表<%end%>
							<% if genre1_2nd_user.is_genre_leader? %>部門長<%end%>
						</td>
					</tr>
				<%end%>
				<% @genre1_1st_users.each do |genre1_1st_user| %>
					<tr>
						<td class="none_wrap"><%= genre1_1st_user.term %></td>
						<td><%=link_to genre1_1st_user.name, user_path(genre1_1st_user.id),class: "user_name" %></td>
						<td><%= genre1_1st_user.genre2_name %></td>
						<td>
							<% if genre1_1st_user.is_admin %>代表<%end%>
							<% if genre1_1st_user.is_genre_leader? %>部門長<%end%>
						</td>
					</tr>
				<%end%>
			</tbody>
		</table>
	</div>
	<div class=member-box>
		<h3>2ジャン</h3>
		<table class="table-sm table-striped">
			<thead>
				<tr>
					<th>代</th>
					<th>名前</th>
					<th>1ジャン</th>
					<th>その他</th>
				</tr>
			</thead>
			<tbody>
				<% @genre2_3rd_users.each do |genre2_3rd_user| %>
					<tr>
						<td class="none_wrap"><%= genre2_3rd_user.term %></td>
						<td><%=link_to genre2_3rd_user.name, user_path(genre2_3rd_user.id),class: "user_name" %></td>
						<td><%= genre2_3rd_user.genre1_name %></td>
						<td>
							<% if genre2_3rd_user.is_admin %>代表<%end%>
							<% if genre2_3rd_user.is_genre_leader? %>部門長<%end%>
						</td>
					</tr>
				<%end%>
				<% @genre2_2nd_users.each do |genre2_2nd_user| %>
					<tr>
						<td class="none_wrap"><%= genre2_2nd_user.term %></td>
						<td><%=link_to genre2_2nd_user.name, user_path(genre2_2nd_user.id),class: "user_name" %></td>
						<td><%= genre2_2nd_user.genre1_name %></td>
						<td>
							<% if genre2_2nd_user.is_admin %>代表<%end%>
							<% if genre2_2nd_user.is_genre_leader? %>部門長<%end%>
						</td>
					</tr>
				<%end%>
				<% @genre2_1st_users.each do |genre2_1st_user| %>
					<tr>
						<td class="none_wrap"><%= genre2_1st_user.term %></td>
						<td><%=link_to genre2_1st_user.name, user_path(genre2_1st_user.id),class: "user_name" %></td>
						<td><%= genre2_1st_user.genre1_name %></td>
						<td>
							<% if genre2_1st_user.is_admin %>代表<%end%>
							<% if genre2_1st_user.is_genre_leader? %>部門長<%end%>
						</td>
					</tr>
				<%end%>
			</tbody>
		</table>
	</div>
	<%if @request_users_info %>
		<div class=member-box>
			<h3>申請中</h3>
			<table class="table-sm table-striped">
				<thead>
					<tr>
						<th>代</th>
						<th>名前</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @request_users_info.each do |request_user_info| %>
						<tr>
							<td class="none_wrap"><%= request_user_info.user.term %></td>
							<td><%=link_to request_user_info.user.name, user_path(request_user_info.user.id),class: "user_name" %></td>
							<td>
								<!--部門長であることの確認処理-->
								<% genre1 = current_user.user_genre_infos.where(priority: 1) %>
								<% if current_user.is_genre_leader? && genre1[0]!=nil && @genre.id == genre1[0].genre_id %>
									<%=button_to '承認', user_genre_info_path(info_id: request_user_info.id, genre_id: @genre.id),method: :patch, class: "btn btn-primary btn-sm" %>
								<%end%>
							</td>
						</tr>
					<%end%>
				</tbody>
			</table>
		</div>
	<%end%>
</div>






<% if current_user.belongs_to_genre?(@genre) %>
<div class="button-center">
  <%=link_to 'ジャンル退会', user_genre_info_path(@genre), method: :delete, class: " my-5 btn btn-danger ", data: {confirm: "退会前に部門長に確認してください。退会しますか？"}%>
  </div>
<%end%>