config/routes.rb
Rails.application.routes.draw do

  root  'home#index'

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update]
  patch 'user/change_is_admin', to: 'users#change_is_admin'

  resources :genres

  patch 'user_genre_infos/add_genre_leader', to: 'user_genre_infos#add_genre_leader'
  patch 'user_genre_infos/destroy_genre_leader', to: 'user_genre_infos#destroy_genre_leader'
  patch 'user_genre_infos/destroy_request', to: 'user_genre_infos#destroy_request'
  resources :user_genre_infos, only: [:create, :update, :destroy]

  resources :events
  get 'event/:id/edit_admins', to: 'events#edit_event_admin', as: :edit_evemt_admins
  resources :event_participations, only: [:create,:update, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :name_kana, presence: true
  validates :student_number, presence: true

  has_many :user_genre_infos #おまじない
  has_many :genres, through: :user_genre_infos, #genre.usersが使えるようになる？
           dependent: :destroy #親モデルを削除する際に、その親モデルに紐づく「子モデル」も一緒に削除できる

  has_many :event_participations
  has_many :events, through: :event_participations, #genre.usersが使えるようになる？
           dependent: :destroy


  def get_genre1_info
    return self.user_genre_infos.find_by(priority: 1)
  end

  def get_genre2_info
    return self.user_genre_infos.find_by(priority: 2)
  end

  def belongs_to_genre?(genre)
    genre1_info = get_genre1_info
    genre2_info = get_genre2_info
    if genre1_info != nil && genre1_info.genre_id == genre.id
        return true
    elsif genre2_info != nil && genre2_info.genre_id == genre.id
        return true
    else
      return false
    end
  end

  def genre1_name
    genre1_info = get_genre1_info
    if genre1_info!=nil && genre1_info.is_valid==true
      genre1_name = genre1_info.genre.name
    elsif genre1_info!=nil && genre1_info.is_valid==false
      genre1_name = genre1_info.genre.name+"申請中"
    elsif genre1_info==nil
      genre1_name = "未登録"
    end
  end

  def genre2_name
    genre2_info = get_genre2_info
    if genre2_info!=nil && genre2_info.is_valid==true
      genre2_name = genre2_info.genre.name
    elsif genre2_info!=nil && genre2_info.is_valid==false
      genre2_name = genre2_info.genre.name+"申請中"
    elsif genre2_info==nil
      genre2_name = "未登録"
    end
  end

  def is_genre_leader?
    if self.user_genre_infos.find_by(is_genre_leader: true) != nil
      user_is_genre_leader = true
    else
      user_is_genre_leader = false
    end
  end

  def is_event_admin(event)
    if self.event_participations.find_by(is_event_admin: true, event_id: event.id)
      return true
    else
      return false
    end
  end

  def joined_event(event)
    if self.event_participations.find_by(user_id: self.id, event_id: event.id)
      return true
    else
      return false
    end
  end

  def event(event_arg)
    event_participation = event_participations.find_by(user_id: self.id, event_id: event_arg.id)
    return event_participation
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit, :update]
	before_action :is_admin?, only: [:change_is_admin]

  def index
  	#@users = User.all
    @users = User.order("term")
    @first = get_1st_grade_term
  end

  def show
  	@user = User.find(params[:id])
    @genre1_name = @user.genre1_name
    @genre2_name = @user.genre2_name

  end

  def edit
  	@user = User.find(params[:id])
  end

  def change_is_admin
  	user = User.find(params[:user_id])
    admin_users = User.where(is_admin: true)
    	if user.is_admin
        #現在代表が1人　かつ　自分が代表の時 代表権限を削除できない
        if admin_users.count==1 and current_user.is_admin
          flash[:warning_notice] = "代表は1人以上必要です"
          redirect_to user_path(current_user) and return
        end
    		user.is_admin = false
    		user.save
    		redirect_to user_path(user) and return
    	else
    		user.is_admin = true
    		user.save
    		redirect_to user_path(user) and return
    	end
  end





  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "情報を更新しました."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end




  private#----------------------

  def user_params
      params.require(:user).permit(:name, :student_number, :name_kana ,:term, :email)
  end

  def correct_user
	  user = User.find(params[:id])
	  if current_user != user
	   redirect_to user_path(current_user)
	  end
	end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_info.html.erb
<% genre1_name = user.genre1_name %>
<% genre2_name = user.genre2_name %>
<h3><%= user.term %>th<%= + ' ' + user.name %></h3>

<table class="table">
	<tbody>
		<tr>
			<td class="none_wrap">1ジャン</td>
			<td>
				<% if genre1_name.include?("申請中") %>
					<span class="genre_name"><%= genre1_name%></span>
					<% if user==current_user %>
						<% genre1_info  = user.get_genre1_info %>
						<%= link_to '取り消し',{controller: "user_genre_infos", action: "destroy_request", info_id: genre1_info.id}, method: :patch, class: "btn btn-outline-danger destroy_genre_request_button btn-sm" %>
					<% end %>
				<% elsif genre1_name == "未登録" and user.id == current_user.id %>
					<details>
						<summary class="genre_request_pull_down">申請</summary>
						<%= form_for(user_genre_info) do |f| %>
					　　 	<%= f.hidden_field :priority, :value => 1 %>
							<%= f.hidden_field :user_id, :value => current_user.id %>
							<%= f.select :genre_id, [["Lock", 1.to_i], ["Hiphop", 2], ["Punking", 3], ["Break", 4], ["Juzz", 5], ["Poping", 6], ["Krump", 7], ["House", 8], ["Girls", 9]], include_blank: "ジャンル選択" %>
					        <%= f.submit "申請する", class: "genre_request_button" %>
					    <% end %>
					</details>
				<% else %>
					<span class="genre_name"><%= genre1_name%></span>
				<% end %>
			</td>
		</tr>
		<tr>
			<td class="none_wrap">2ジャン</td>
			<td>
				<% if genre2_name.include?("申請中") %>
					<span class="genre_name"><%= genre2_name%></span>
					<% if user==current_user %>
						<% genre2_info  = user.get_genre2_info %>
					<%= link_to '取り消し',{controller: "user_genre_infos", action: "destroy_request", info_id: genre2_info.id}, method: :patch, class: "btn btn-outline-danger destroy_genre_request_button btn-sm" %>
					<% end %>
				<% elsif genre2_name == "未登録" and user.id == current_user.id  %>
					<details>
						<summary class="genre_request_pull_down">申請</summary>
						<%= form_for(user_genre_info) do |f| %>
					　　 	<%= f.hidden_field :priority, :value => 2 %>
							<%= f.hidden_field :user_id, :value => current_user.id %>
							<%= f.select :genre_id, [["Lock", 1.to_i], ["Hiphop", 2], ["Punking", 3], ["Break", 4], ["Juzz", 5], ["Poping", 6], ["Krump", 7], ["House", 8], ["Girls", 9]], include_blank: "ジャンル選択" %>
					        <%= f.submit "申請する", class: "genre_request_button" %>
						 <% end %>
					</details>
				<% else %>
					<span class="genre_name"><%= genre2_name%></span>
				<% end %>
			</td>
		</tr>
		<tr>
			<td>その他</td>
			<td>
				<%if user.is_admin %> <%= "代表　" %><%end%>
				<%if user.is_genre_leader? %> 部門長 <%end%>
			</td>
		</tr>
	</tbody>
</table>

<% if flash[:notice]%>
	<div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:warning_notice]%>
	<div class="alert alert-warning">
      <%= flash[:warning_notice] %>
    </div>
<% end %>
<% if flash[:danger_notice]%>
	<div class="alert alert-danger">
      <%= flash[:danger_notice] %>
    </div>
<% end %>

<% if user == current_user %>
	<%=link_to '', edit_user_path(user.id), class: "fas fa-edit btn btn-outline-secondary btn-block text-dark"%>

	<div class="mt-2 mb-2">
	<%=link_to 'イベント作成', new_event_path, class: "btn btn-outline-secondary btn-block text-dark"%>
	</div>
<% end %>



<%if current_user.is_admin==true %>
	<div class="mb-4 mt-3">
		<details>
		  <summary>代表権限の機能</summary>
			<%if current_user.is_admin==true && user.is_admin==true%>
				<%=  link_to 'このユーザーの代表権限を削除', user_change_is_admin_path(user_id: user.id), method: :patch, class: "mt-2 btn btn-sm btn-outline-danger"%></br>
			<%end%>
			<%if current_user.is_admin==true && user.is_admin==false%>
				<%=  link_to 'このユーザーに代表権限を付与', user_change_is_admin_path(user_id: user.id), method: :patch, class: "mt-2 btn btn-sm btn-outline-success" %></br>
			<%end%>
			<%if current_user.is_admin==true && user.is_genre_leader? == true%>
				<%=  link_to 'このユーザーの部門長権限を削除', {controller: "user_genre_infos",
											   action: "destroy_genre_leader", user_id: user.id}, method: :patch, class: "mt-2 btn btn-sm btn-outline-danger" %></br>
			<%end%>
			<%if current_user.is_admin==true && user.is_genre_leader? == false%>
				<%=  link_to 'このユーザーに部門長権限を付与', {controller: "user_genre_infos",
											   action: "add_genre_leader", user_id: user.id}, method: :patch, class: "mt-2 btn btn-sm btn-outline-success" %></br>
			<%end%></br>
		</details>
	</div>
<% end %>

app/views/users/edit.html.erb
<h3>登録情報の編集</h3>


<%= form_for(@user) do |f| %>
  <div class='user_edit'>

    <div class="field user_form">
      <div class='user_form_label'><%= f.label :student_number, "学修番号" %></div>
      	<%= f.text_field :student_number, autofocus: true, autocomplete: "student_number" %>
    </div>

    <div class="field user_form">
      <div class='user_form_label'><%= f.label :name,"名前" %></div>
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field user_form">
      <div class='user_form_label'><%= f.label :name_kana, "名前（カナ）" %></div>
      <%= f.text_field :name_kana, autofocus: true, autocomplete: "name_kana" %>
    </div>

    <div class="field user_form">
      <div class='user_form_label'><%= f.label :term,"期" %></div>
      <%= f.text_field :term, autofocus: true, autocomplete: "term" %>
    </div>


    <div class="field user_form">
      <div class='user_form_label'><%= f.label :email, "メールアドレス" %></div>
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="actions user_form">
      <%= f.submit "変更する" ,class: "m-2"%>
    </div>

</div>
<% end %>

app/views/users/index.html.erb
<div class="container">
	<div class='row'>
		<div class='col-lg-4'>
			<%= render 'users/user_info', user: current_user, user_genre_info: UserGenreInfo.new %>
		</div>
		<div class='col-lg-8'>


			<h3>部員一覧</h3>
			<table class="table">
				<thead>
					<tr>
						<th>代</th>
						<th>名前</th>
						<th>ジャンル</th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<tr>
							<td class="none_wrap"><%= user.term %></td>
							<td><%=link_to user.name, user_path(user.id),class: "user_name" %></td>
							<td>1:<%= user.genre1_name %></br>2:<%= user.genre2_name %></td>
							<!-- <td>
								<% if user.is_admin %>代表<%end%>
								<% if user.is_genre_leader? %>部門長<%end%>
							</td> -->
						</tr>
					<%end%>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class='row'>
		<div class='col-lg-4'>
			<%= render 'users/user_info', user: @user, user_genre_info: UserGenreInfo.new %>
		</div>
		<div class="col-lg-8">
			<table class="table">
				<thead>
					<tr>
						<th>日程</th>
						<th>参加イベント</th>
					</tr>
				</thead>
				<tbody>
					<% @user.events.order(start_at: "DESC").each do |event| %>
						<tr>
							<td class="none_wrap">
								<% if event.start_at == event.end_at%>
									<%= event.start_at.strftime("%Y/%m/%d") %>
								<% else %>
									<%= event.start_at.strftime("%Y/%m/%d") %></br>
									<%= event.end_at.strftime("~%d") %>
								<% end %>
							</td>
							<td><%=link_to event.name, event_path(event) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>