config/routes.rb
Rails.application.routes.draw do

  root  'home#index'

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update]
  patch 'user/change_is_admin', to: 'users#change_is_admin'

  resources :genres

  patch 'user_genre_infos/add_genre_leader', to: 'user_genre_infos#add_genre_leader'
  patch 'user_genre_infos/destroy_genre_leader', to: 'user_genre_infos#destroy_genre_leader'
  patch 'user_genre_infos/destroy_request', to: 'user_genre_infos#destroy_request'
  resources :user_genre_infos, only: [:create, :update, :destroy]

  resources :events
  get 'event/:id/edit_admins', to: 'events#edit_event_admin', as: :edit_evemt_admins
  resources :event_participations, only: [:create,:update, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
	validates :name, presence: true
	validates :description, presence: true
	validates :start_at, presence: true
	validates :end_at, presence: true

	has_many :event_participations
	has_many :users, through: :event_participations, #genre.usersが使えるようになる？
					 dependent: :destroy

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :destroy, :update]

  def index
    @active_event = Event.where('end_at >= ?', Date.today).order(:start_at)
    @past_event = Event.where('end_at < ?', Date.today).order(:start_at)
  end

  def new
    @event = Event.new
  end

  def create
    # Binding.pry
      @events = Event.all
      @event = Event.new(event_params)
      if @event.save
        flash[:notice] = "イベントを作成しました"
        event_prticipation = EventParticipation.new
        event_prticipation.user_id = current_user.id
        event_prticipation.event_id = @event.id
        event_prticipation.is_event_admin = true
        if event_prticipation.save
          redirect_to event_path(@event)
        else
          #ここの処理が実行されることはないはずだが、、、
          flash[:danger_notice] = 'イベント作成でエラーが発生しました。やり直してください。改善しない場合はアプリ開発者に連絡してください。'
          redirect_to user_path(current_user)
        end
      else
        render :new
      end
  end

  def show
    @event = Event.find(params[:id])
    @admin_participations = @event.event_participations.where(is_event_admin: true)
    @new_event_participation = EventParticipation.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def edit_event_admin
    @event = @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
        flash[:notice] = "変更を保存しました"
        redirect_to event_path(@event)
    else
      render :new
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    flash[:notice] = "イベントを削除しました"
    redirect_to events_path

  end

  private
  def event_params
   params.require(:event).permit(:name, :description, :start_at, :end_at, :url1, :url1_description, :url2, :url2_description, :url3, :url3_description)
  end

  def correct_user#event管理者or代表のみ編集、削除可能
    event = Event.find(params[:id])
    if !(current_user.is_event_admin(event) or current_user.is_admin)
      # flash[:danger_notice] = "イベントの編集,削除権限がありません"
      redirect_to event_path(event)
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="event_form">
	<%= form_for(@event) do |f| %>

		<div class="field  text-center">
        <%= f.label :name,'イベント名' %><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
      </div>

      <div class="field  text-center">
        <%= f.label :description,'概要または連絡事項' %><br />
        <%= f.text_area :description, autofocus: true, autocomplete: "description" %>
      </div>

      <div class="field text-center">
        <%= f.label :start_at,'イベント開始日' %><br />
       <%= f.date_select :start_at, {}%>
      </div>

      <div class="field text-center">
        <%= f.label :end_at,'イベント終了日' %><br />
       <%= f.date_select :end_at, {}%>
      </div>

      <div class="mt-3">
          <div class="field mt-2">
            <%= f.label :url1,'リンク1', class: "url_description"%><br>
            <%= f.url_field :url1, autofocus: true, autocomplete: "url1"%><br>
            <%= f.label :url1_description,'リンク1の表示' , class: "url_description"%><br>
            <%= f.text_field :url1_description, autofocus: true, autocomplete: "description", id: "url_description_field" %><br>
          </div>
          <div class="field mt-2">
            <%= f.label :url2,'リンク2', class: "url_description"%><br>
            <%= f.url_field :url2, autofocus: true, autocomplete: "url2"%><br>
            <%= f.label :url2_description,'リンク2の表示' , class: "url_description"%><br>
            <%= f.text_field :url2_description, autofocus: true, autocomplete: "description", id: "url_description_field" %><br>
          </div>
          <div class="field mt-2">
            <%= f.label :url3,'リンク3', class: "url url_description"%><br>
            <%= f.url_field :url3, autofocus: true, autocomplete: "url3" %><br>
            <%= f.label :url3_description,'リンク3の表示' , class: "url_description"%><br>
            <%= f.text_field :url3_description, autofocus: true, autocomplete: "description", id: "url_description_field" %><br>
          </div>
      </div>

      <div class="actions text-center">
        <%= f.submit "保存" ,class: "btn btn-outline-info "%>
      </div>

      <% if @event.errors.any? %>
        <div id="error_explanation">
          <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li class="text-danger"><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
	<% end %>
</div>
<!-- フラッシュメッセージの表示 -->
<% if flash[:event_participation_error]%>
  <div class="alert alert-danger">
      <%= flash[:event_participation_error] %>
    </div>
<% end %>

app/views/events/edit_event_admin.html.erb
<div class="event_participants">
管理者の編集
    <table class="table table-sm">
      <thead>
        <tr>
          <th>代</th>
          <th>名前</th>
          <th>管理者権限</th>
        </tr>
      </thead>
      <tbody>
        <% @event.event_participations.reverse_each do |event_participation| %>
        <tr>
          <td><%= event_participation.user.term %></td>
          <td><%= event_participation.user.name %></td>
          <td>
            <%if event_participation.is_event_admin %>
                <%= form_for(event_participation) do |f| %>
                  <%= f.hidden_field :event_id, :value => @event.id %>
                  <%= f.hidden_field :is_event_admin, :value => false %>
                  <%= f.submit "-" ,class: "btn btn-outline-warning btn-sm event_admin_assignment" %>
                <% end %>
            <% else %>
                <%= form_for(event_participation) do |f| %>
                  <%= f.hidden_field :event_id, :value => @event.id %>
                  <%= f.hidden_field :is_event_admin, :value => true %>
                  <%= f.submit "+" ,class: "btn btn-outline-success btn-sm event_admin_assignment" %>
                <% end %>
            <%end%>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/events/index.html.erb
<h3>イベント一覧</h3>
<% if flash[:notice]%>
	<div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:warning_notice]%>
	<div class="alert alert-warning">
      <%= flash[:warning_notice] %>
    </div>
<% end %>
<% if flash[:danger_notice]%>
	<div class="alert alert-danger">
      <%= flash[:danger_notice] %>
    </div>
<% end %>
<div class="container">
	<div class='row'>

		<table class="table">
			<thead>
				<tr>
					<th>日程</th>
					<th>イベント名</th>
					<th>人数</th>
				</tr>
			</thead>
			<tbody>
				<% @active_event.each do |event| %>
					<tr>
						<td class="none_wrap">
							<% if event.start_at == event.end_at%>
								<%= event.start_at.strftime("%m/%d") %>
							<% else %>
								<%= event.start_at.strftime("%m/%d") %></br>
								<%= event.end_at.strftime("~%d") %>
							<% end %>
						</td>
						<td><%=link_to event.name, event_path(event) %></td>
						<td><%= event.users.count %></td>
					</tr>
				<% end %>
			</tbody>
		</table>


		<details style="margin-top:1rem;">
		<summary>過去のイベント：<%=@past_event.count %>件</summary>
		<table class="table">
			<thead>
				<tr>
					<th>日程</th>
					<th>イベント名</th>
					<th>人数</th>
				</tr>
			</thead>
			<tbody>
				<% @past_event.reverse_each do |event| %>
					<tr>
						<td class="none_wrap">
							<% if event.start_at == event.end_at%>
								<%= event.start_at.strftime("%m/%d") %>
							<% else %>
								<%= event.start_at.strftime("%m/%d") %></br>
								<%= event.end_at.strftime("~%d") %>
							<% end %>
						</td>
						<td><%=link_to event.name, event_path(event) %></td>
						<td><%= event.users.count %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		</details>

	</div>
</div>

app/views/events/new.html.erb
<div class="event_form">
	<%= form_for(@event, url: events_path(@event), method: :post ) do |f| %>
		<div class="field  text-center">
        <%= f.label :name,'イベント名' %><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
      </div>

      <div class="field  text-center">
        <%= f.label :description,'概要または連絡事項' %><br />
        <%= f.text_area :description, autofocus: true, autocomplete: "description" %>
      </div>

      <div class="field text-center">
        <%= f.label :start_at,'イベント開始日' %><br />
       <%= f.date_select :start_at, {}%>
      </div>

      <div class="field text-center">
        <%= f.label :end_at,'イベント終了日' %><br />
       <%= f.date_select :end_at, {}%>
      </div>

      <div class="mt-3">
          <div class="field mt-2">
            <%= f.label :url1,'リンク1', class: "url_description"%>
            <br><span class="URL-comment"> 参加者に表示したいリンクがあればここに入れます（Googleフォームなど）</span><br>
            <%= f.url_field :url1, autofocus: true, autocomplete: "url1"%><br>
            <%= f.label :url1_description,'リンク1の表示' , class: "url_description"%><br>
            <%= f.text_field :url1_description, autofocus: true, autocomplete: "description", id: "url_description_field" %><br>
          </div>
          <div class="field mt-2">
            <%= f.label :url2,'リンク2', class: "url_description"%><br>
            <%= f.url_field :url2, autofocus: true, autocomplete: "url2"%><br>
            <%= f.label :url2_description,'リンク2の表示' , class: "url_description"%><br>
            <%= f.text_field :url2_description, autofocus: true, autocomplete: "description", id: "url_description_field" %><br>
          </div>
          <div class="field mt-2">
            <%= f.label :url3,'リンク3', class: "url url_description"%><br>
            <%= f.url_field :url3, autofocus: true, autocomplete: "url3" %><br>
            <%= f.label :url3_description,'リンク3の表示' , class: "url_description"%><br>
            <%= f.text_field :url3_description, autofocus: true, autocomplete: "description", id: "url_description_field" %><br>
          </div>
      </div>

		  <div class="actions text-center">
	      <%= f.submit "作成する" ,class: "btn btn-outline-info "%>
	    </div>

      <% if @event.errors.any? %>
        <div id="error_explanation">
          <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li class="text-danger"><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

	<% end %>

</div>

app/views/events/show.html.erb
<!-- フラッシュメッセージの表示 -->
<% if flash[:event_participation_error]%>
	<div class="alert alert-danger">
      <%= flash[:event_participation_error] %>
    </div>
<% end %>
<% if flash[:notice]%>
	<div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
<% end %>

<div class="mb-3">
	<h3 class="event_name" style="display:inline;"><%= @event.name %></h3>

	<% if @event.start_at == @event.end_at%>
		<span>：<%= @event.start_at.strftime("%Y年%m月%d日") %></span>
	<% else %>
		<span>：<%= @event.start_at.strftime("%Y年%m月%d日 ~") %>
				<%= @event.end_at.strftime("%d日") %></span>
	<% end %>
</div>

<div class="event_dexscription">
	<p><%= safe_join(@event.description.split("\n"),tag(:br)) %></p>
</div>

<% if current_user.joined_event(@event) %>
	<div class="text-center">
		<div class="mt-2 mb-2">
			<a href="<%= @event.url1 %>" target="_blank"> <%= @event.url1_description %> </a>
		</div>
		<div class="mt-2 mb-2">
			<a href="<%= @event.url2 %>" target="_blank"> <%= @event.url2_description %> </a>
		</div>
		<div class="mt-2 mb-2">
			<a href="<%= @event.url3 %>" target="_blank"> <%= @event.url3_description %> </a>
		</div>
	</div>
<% end %>

<!-- 参加ボタン -->

<% if !(current_user.joined_event(@event)) %>
	<%= form_for(@new_event_participation, url: event_participations_path(@new_event_participation)) do |f| %>
		<%= f.hidden_field :user_id, :value => current_user.id %>
		<%= f.hidden_field :event_id, :value => @event.id %>
	  	<div class="actions text-center">
	  		<%= f.submit "参加する" ,class: "btn btn-outline-info" %>
		</div>
	<% end %>
<% end %>



<!-- 管理者一覧 -->
<div class="mt-3">イベント管理者
<% if current_user.is_event_admin(@event) %>
	<%= link_to '編集', edit_evemt_admins_path(@event), class: 'ml-2'%>
<% end %>
</div>
	<table class="table table-bordered table-sm" >
		<thead>
			<tr>
				<th>代</th>
				<th>名前</th>
			</tr>
		</thead>
		<tbody>
			<% @admin_participations.each do |admin_participation| %>
				<tr>
					<td class="none_wrap"><%= admin_participation.user.term %></td>
					<td><%=link_to admin_participation.user.name, user_path(admin_participation.user),class: "user_name" %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

<!-- 参加者一覧 -->
<div class="event_participants">
	<details>
	  <summary>参加者：<%=@event.users.count %>名</summary>
	  <p class="event_admins">
		<table class="table">
			<thead>
				<tr>
					<th>代</th>
					<th>名前</th>
					<th>ジャンル</th>
				</tr>
			</thead>
			<tbody>
				<% @event.users.reverse_each do |user| %>
				<tr>
					<td class="none_wrap"><%= user.term %></td>
					<td><%= link_to user.name, user_path(user),class: "user_name" %></td>
					<td><%= user.genre1_name %>／<%= user.genre2_name %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	  </p>
	</details>
</div>


<div class="text-center">
	<!-- ショーケース作成ボタン -->
	<% if false %>
		<% if (current_user.joined_event(@event)) %>
			 <p><%= link_to "ショーケース作成", user_path(current_user),class: "btn btn-outline-info" %></p>
		<% end %>
	<% end %>

	<!-- 参加取り下げボタン -->
	<% if current_user.joined_event(@event) %>
	<p><%= link_to "参加取り下げ", event_participation_path(current_user.event(@event),event_id: @event.id ), method: :delete, data: { confirm: '参加を取りやめる前に管理者に連絡してください。
		参加を取りやめますか？' } ,class: "btn btn-outline-warning" %></p>
	<% end %>

	<!-- 編集、削除ボタン -->
	<% if current_user.is_event_admin(@event) or current_user.is_admin %>
		<%= link_to '編集', edit_event_path(@event.id), class: "btn btn-outline-success" %>
		<%= link_to '削除', event_path(@event.id), method: :delete, data: { confirm: 'このイベントを削除してよろしいですか？' }, class: " btn btn-outline-danger" %>
		<p style="font-size: 8px; color: #808080; margin-top: 4px;">代表またはイベント管理者はイベントの編集、削除ができます</p>
	<% end %>

</div>