config/routes.rb
Rails.application.routes.draw do

  root  'home#index'

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update]
  patch 'user/change_is_admin', to: 'users#change_is_admin'

  resources :genres

  patch 'user_genre_infos/add_genre_leader', to: 'user_genre_infos#add_genre_leader'
  patch 'user_genre_infos/destroy_genre_leader', to: 'user_genre_infos#destroy_genre_leader'
  patch 'user_genre_infos/destroy_request', to: 'user_genre_infos#destroy_request'
  resources :user_genre_infos, only: [:create, :update, :destroy]

  resources :events
  get 'event/:id/edit_admins', to: 'events#edit_event_admin', as: :edit_evemt_admins
  resources :event_participations, only: [:create,:update, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FF部員管理</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar  navbar-dark bg-secondary" >
      <div class="container">
          <p class="navbar-brand lead ff" >FinalFlash</p>
        <ul class="nav justify-content-end ">
          <% if user_signed_in? %>
            <li><%=link_to 'マイページ', user_path(current_user.id), class: "fas fa-user-alt mx-3 text-light" %></li>
            <li><%=link_to ' 部員', users_path,class: "fas fa-user-friends mx-3 text-light" %></li>
            <li><%=link_to ' ジャンル', genres_path,class: "mx-3 text-light" %></li>
            <li><%=link_to ' イベント', events_path,class: "mx-3 text-light" %></li>
            <li><%=link_to ' ログアウト', destroy_user_session_path, method: :delete,class: "fas fa-sign-out-alt mx-3 text-light" %></li>
          <% else %>
            <li><%=link_to ' Home', '/', class: "fas fa-home mx-3 text-light"%></li>
            <li><%=link_to ' 部員登録', new_user_registration_path,class: "fas fa-user-plus mx-3 text-light" %></li>
            <li><%=link_to ' ログイン', new_user_session_path,class: "fas fa-sign-in-alt mx-3 text-light" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container mt-3">
    <!--   <div  class="mt-3"> -->
       <%= yield %>
     <!--  </div> -->
     <div style="height:20px;"></div>
    </div>

  </body>
</html>